dist: bionic

sudo: required

language: cpp

env:
  global:
    - RELEASE_BRANCH="master"

before_install:
  # replacing default gcc and g++
  - sudo add-apt-repository universe
  - sudo add-apt-repository multiverse
  - sudo apt-get update
  - sudo apt-get -y upgrade
  - sudo apt-get -y dist-upgrade
  - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
  - sudo apt install -y --install-recommends gcc-9 gcc-9-multilib g++-9 g++-9-multilib
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - gcc --version
  - g++ --version

#install:
#before_script:

script:
  - bash f11_wine_builder.sh 5.11
  - mkdir result
  - mv wine-staging-5.11.tar.xz ./result/

after_success:
  # md5sum tool
  - wget -c https://github.com/ferion11/libsutil/releases/download/md5sum_util_v0.1/md5sum_util.sh
  - bash md5sum_util.sh result

  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh

  - |- # publish
    if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
      export UPLOADTOOL_BODY="Instructions on the README can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions on the README can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    else
      echo 'Publishing release to GitHub...'
      export UPLOADTOOL_BODY="Instructions on the README can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
      bash upload.sh result/*
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always